"""intermediate tables has been added

Revision ID: 2ecec6aba723
Revises: 4e25a67d2e40
Create Date: 2023-09-30 11:30:59.965472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecec6aba723'
down_revision = '4e25a67d2e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boatxfaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('boat_id', sa.BigInteger(), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boat.boat_id'], ),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boat_id', 'faction_id', name='uq_boat_faction')
    )
    op.create_table('infantryxfaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('infantry_id', sa.BigInteger(), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.ForeignKeyConstraint(['infantry_id'], ['infantry.infantry_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('infantry_id', 'faction_id', name='uq_infantry_faction')
    )
    op.create_table('planexfaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plane_id', sa.BigInteger(), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.ForeignKeyConstraint(['plane_id'], ['plane.plane_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plane_id', 'faction_id', name='uq_plane_faction')
    )
    op.create_table('structurexfaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.structure_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'faction_id', name='uq_structure_faction')
    )
    op.create_table('tankxfaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tank_id', sa.BigInteger(), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tank.tank_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tank_id', 'faction_id', name='uq_tank_faction')
    )
    with op.batch_alter_table('boat', schema=None) as batch_op:
        batch_op.drop_constraint('boat_faction_id_fkey', type_='foreignkey')
        batch_op.drop_column('faction_id')
        batch_op.drop_column('custom_cost')

    with op.batch_alter_table('infantry', schema=None) as batch_op:
        batch_op.drop_constraint('infantry_faction_id_fkey', type_='foreignkey')
        batch_op.drop_column('faction_id')
        batch_op.drop_column('custom_cost')

    with op.batch_alter_table('plane', schema=None) as batch_op:
        batch_op.drop_constraint('plane_faction_id_fkey', type_='foreignkey')
        batch_op.drop_column('faction_id')
        batch_op.drop_column('custom_cost')

    with op.batch_alter_table('structure', schema=None) as batch_op:
        batch_op.drop_constraint('structure_faction_id_fkey', type_='foreignkey')
        batch_op.drop_column('faction_id')
        batch_op.drop_column('custom_cost')

    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_constraint('tank_faction_id_fkey', type_='foreignkey')
        batch_op.drop_column('faction_id')
        batch_op.drop_column('custom_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_cost', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('faction_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tank_faction_id_fkey', 'faction', ['faction_id'], ['faction_id'])

    with op.batch_alter_table('structure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_cost', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('faction_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('structure_faction_id_fkey', 'faction', ['faction_id'], ['faction_id'])

    with op.batch_alter_table('plane', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_cost', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('faction_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('plane_faction_id_fkey', 'faction', ['faction_id'], ['faction_id'])

    with op.batch_alter_table('infantry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_cost', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('faction_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('infantry_faction_id_fkey', 'faction', ['faction_id'], ['faction_id'])

    with op.batch_alter_table('boat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_cost', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('faction_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('boat_faction_id_fkey', 'faction', ['faction_id'], ['faction_id'])

    op.drop_table('tankxfaction')
    op.drop_table('structurexfaction')
    op.drop_table('planexfaction')
    op.drop_table('infantryxfaction')
    op.drop_table('boatxfaction')
    # ### end Alembic commands ###
