"""initial db

Revision ID: 4e25a67d2e40
Revises: 
Create Date: 2023-09-28 18:07:07.417618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e25a67d2e40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('game_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('faction',
    sa.Column('faction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.PrimaryKeyConstraint('faction_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'game_id', name='uq_name_game_id')
    )
    op.create_table('boat',
    sa.Column('boat_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('can_go_ground', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('is_stealth', sa.Boolean(), nullable=False),
    sa.Column('build_limit', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.PrimaryKeyConstraint('boat_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('infantry',
    sa.Column('infantry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('can_swim', sa.Boolean(), nullable=False),
    sa.Column('can_fly', sa.Boolean(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('is_stealth', sa.Boolean(), nullable=False),
    sa.Column('build_limit', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.PrimaryKeyConstraint('infantry_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plane',
    sa.Column('plane_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('is_stealth', sa.Boolean(), nullable=False),
    sa.Column('build_limit', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.PrimaryKeyConstraint('plane_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('structure',
    sa.Column('structure_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('build_on_water', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('is_stealth', sa.Boolean(), nullable=False),
    sa.Column('build_limit', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.PrimaryKeyConstraint('structure_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tank',
    sa.Column('tank_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('can_swim', sa.Boolean(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=True),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('custom_cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('is_stealth', sa.Boolean(), nullable=False),
    sa.Column('build_limit', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.faction_id'], ),
    sa.PrimaryKeyConstraint('tank_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tank')
    op.drop_table('structure')
    op.drop_table('plane')
    op.drop_table('infantry')
    op.drop_table('boat')
    op.drop_table('faction')
    op.drop_table('game')
    # ### end Alembic commands ###
