"""is_special should be available for each unit type

Revision ID: 8a6c21847fa6
Revises: 2ecec6aba723
Create Date: 2023-10-05 22:42:34.594152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6c21847fa6'
down_revision = '2ecec6aba723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special', sa.Boolean(), nullable=True))

    with op.batch_alter_table('infantry', schema=None) as batch_op:
        batch_op.alter_column('is_special',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('plane', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special', sa.Boolean(), nullable=True))

    with op.batch_alter_table('structure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.alter_column('is_special',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.alter_column('is_special',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('structure', schema=None) as batch_op:
        batch_op.drop_column('is_special')

    with op.batch_alter_table('plane', schema=None) as batch_op:
        batch_op.drop_column('is_special')

    with op.batch_alter_table('infantry', schema=None) as batch_op:
        batch_op.alter_column('is_special',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('boat', schema=None) as batch_op:
        batch_op.drop_column('is_special')

    # ### end Alembic commands ###
