"""Not null restrict to certain fields

Revision ID: d87943ac79b1
Revises: 74147848bb10
Create Date: 2023-12-03 23:10:05.723935

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d87943ac79b1"
down_revision = "74147848bb10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("boat", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table("boatxfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("faction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("infantry", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table("infantryxfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("plane", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table("planexfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("structure", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table("structurexfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("tank", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table("tankxfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tankxfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("tank", schema=None) as batch_op:
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("structurexfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("structure", schema=None) as batch_op:
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("planexfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("plane", schema=None) as batch_op:
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("infantryxfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("infantry", schema=None) as batch_op:
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("faction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("boatxfaction", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("boat", schema=None) as batch_op:
        batch_op.alter_column(
            "target_air_unit", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    # ### end Alembic commands ###
